before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - id: build
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      # - windows
      # - darwin
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - "6"
      - "7"
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64

dockers:
  - image_templates:
      - "ghcr.io/getais/{{ .ProjectName }}/velero-plugin:{{ .Version }}-amd64"
      - "ghcr.io/getais/{{ .ProjectName }}/velero-plugin:latest-amd64"
    use: buildx
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.url=https://github.com/getais/velero-plugin-annotations-prune"
      - "--label=org.opencontainers.image.source=https://github.com/getais/velero-plugin-annotations-prune"
      - "--label=org.opencontainers.image.authors=Tomas Liumparas <tomas.liumparas@gmail.com>"
  - image_templates:
      - "ghcr.io/getais/{{ .ProjectName }}/velero-plugin:{{ .Version }}-arm64v8"
      - "ghcr.io/getais/{{ .ProjectName }}/velero-plugin:latest-arm64v8"
    use: buildx
    goarch: arm64
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/arm64/v8"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.url=https://github.com/getais/velero-plugin-annotations-prune"
      - "--label=org.opencontainers.image.source=https://github.com/getais/velero-plugin-annotations-prune"
      - "--label=org.opencontainers.image.authors=Tomas Liumparas <tomas.liumparas@gmail.com>"
  - image_templates:
      - "ghcr.io/getais/{{ .ProjectName }}/velero-plugin:{{ .Version }}-armv6"
      - "ghcr.io/getais/{{ .ProjectName }}/velero-plugin:latest-armv6"
    use: buildx
    goarch: arm
    goarm: "6"
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/arm/v6"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.url=https://github.com/getais/velero-plugin-annotations-prune"
      - "--label=org.opencontainers.image.source=https://github.com/getais/velero-plugin-annotations-prune"
      - "--label=org.opencontainers.image.authors=Tomas Liumparas <tomas.liumparas@gmail.com>"
  - image_templates:
      - "ghcr.io/getais/{{ .ProjectName }}/velero-plugin:{{ .Version }}-armv7"
      - "ghcr.io/getais/{{ .ProjectName }}/velero-plugin:latest-armv7"
    use: buildx
    goarch: arm
    goarm: "7"
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/arm/v7"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.url=https://github.com/getais/velero-plugin-annotations-prune"
      - "--label=org.opencontainers.image.source=https://github.com/getais/velero-plugin-annotations-prune"
      - "--label=org.opencontainers.image.authors=Tomas Liumparas <tomas.liumparas@gmail.com>"

docker_manifests:
  - name_template: "ghcr.io/getais/{{ .ProjectName }}/velero-plugin:{{ .Version }}"
    image_templates:
      - "ghcr.io/getais/{{ .ProjectName }}/velero-plugin:{{ .Version }}-amd64"
      - "ghcr.io/getais/{{ .ProjectName }}/velero-plugin:{{ .Version }}-arm64v8"
      - "ghcr.io/getais/{{ .ProjectName }}/velero-plugin:{{ .Version }}-armv6"
      - "ghcr.io/getais/{{ .ProjectName }}/velero-plugin:{{ .Version }}-armv7"

  - name_template: "ghcr.io/getais/{{ .ProjectName }}/velero-plugin:latest"
    image_templates:
      - "ghcr.io/getais/{{ .ProjectName }}/velero-plugin:latest-amd64"
      - "ghcr.io/getais/{{ .ProjectName }}/velero-plugin:latest-arm64v8"
      - "ghcr.io/getais/{{ .ProjectName }}/velero-plugin:latest-armv6"
      - "ghcr.io/getais/{{ .ProjectName }}/velero-plugin:latest-armv7"

release:
  disable: false
  prerelease: auto
  mode: replace
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
